### ISSUE TITLE
[Feature Request] Make a desktop version

### ISSUE THREAD

**Issue by UniqueName12345** [PPPDUD/WorldExplorer#1]
It would be great to be able to [view / make] cubeupload images from my main scratching device.

**Comment by PPPDUD** [comment]
Hmm... intresting idea. I will try, but no promises.

**Comment by PPPDUD** [comment]
Windows installer coming soon.. any other OSes that should be supported?

**Comment by UniqueName12345** [comment]
> Windows installer coming soon.. any other OSes that should be supported?

_Maybe_ Linux, but I use Windows, so 😜.

**Comment by UniqueName12345** [comment]
> Windows installer coming soon.. any other OSes that should be supported?

I just realized that Norton Family logs what apps someone installs, so it would most likely have to be a portable zip file or a .paf.exe file

**Comment by PPPDUD** [comment]
The production was delayed, but I'm trying!

**Comment by PPPDUD** [comment]
Sadly, this seems unlikely at the moment. However, you can still use an emulator for desktop operation.

**Comment by PPPDUD** [comment]
Thhh

**Comment by PPPDUD** [comment]
Closed

**Comment by PPPDUD** [comment]
Close

**Comment by PPPDUD** [comment]
It's not working..

**Comment by PPPDUD** [comment]
Close now!

**Comment by PPPDUD** [comment]
Oh, I see the issue.
